language: cpp
os:
        - linux
compiler:
        - gcc
env:
        - PROJECT=xonotic
before_install:
        - test `uname` != 'Linux' || sudo apt-get update -qq
        - test `uname` != 'Linux' || sudo apt-get install -y gcc-mingw-w64 g++-mingw-w64 g++-mingw-w64-i686 g++-mingw-w64-x86-64 gcc-mingw-w64-i686 gcc-mingw-w64-x86-64
        - git archive --format=tar https://gitlab.com/xonotic/xonotic.git master misc/builddeps
        - git archive --format=tar --remote=git://de.git.xonotic.org/xonotic/xonotic.git --prefix=.deps/ master:misc/builddeps | tar xvf -
        - for X in .deps/*; do rsync --remove-source-files -vaSHP -L "$X"/*/ "$X"/ || true; done
install:
        - true
before_script:
        - true
script:
        - test `uname` != 'Linux' || "./.travis-script-${PROJECT}.sh" linux32
        - test `uname` != 'Linux' || "./.travis-script-${PROJECT}.sh" linux64
        - test `uname` != 'Linux' || "./.travis-script-${PROJECT}.sh" win32
        - test `uname` != 'Linux' || "./.travis-script-${PROJECT}.sh" win64
        - test `uname` != 'Darwin' || "./.travis-script-${PROJECT}.sh" osx
after_success:
        - ./.travis-after_success-${PROJECT}.sh
after_failure:
        - true
after_script:
        - true
